name: Release

on:
# push:
#   tags:
#     - 'v*'
 workflow_dispatch:
   branches:
     - main
  
  
jobs:
  build:
    name: Build - ${{ matrix.targetPlatform }} - Unity ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    environment: Unity build
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 6000.0.23f1
        targetPlatform:
          - WebGL
          - StandaloneLinux64
          - StandaloneWindows
    steps:

      # Release    
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}

      - name: List Files
        run: |
          ls -lha build

      - name: Release
        uses: softprops/action-gh-release@v2
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          # Identify if this is a pre release by checking if the tag name contains -rc, -b, -a
          # prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-b') || contains(github.ref, '-a') }}
          files: build/${{ matrix.targetPlatform }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}